add coverage

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -26,7 +26,7 @@ jobs:
       - name: Install dependencies
         run: |
           python -m pip install --upgrade pip
-          pip install flake8 pytest coverage coverage-badge
+          pip install flake8 pytest coverage coverage-badge pytest-cov
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
       
       - name: Lint with flake8
@@ -36,13 +36,15 @@ jobs:
           # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
           # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
           flake8 . --count --exit-zero --show-source --max-complexity=10 --max-line-length=127 > lint.txt
+
       - name: Test with pytest
-        run: |
-          pytest
-        
+        id: tests
+        run: pytest
+        # continue-on-error: true
+
       - name: Coverage
         run:  | 
-          coverage run -m pytest
+          coverage run --source=app -m pytest
           coverage report --skip-covered > coverage.txt
           coverage-badge > coverage.svg
 
@@ -58,12 +60,12 @@ jobs:
       #     name: coverage-badge
       #     path: coverage.svg
 
-      - name: Find Current Pull Request
-        uses: jwalton/gh-find-current-pr@v1.2.1
-        id: findPr
-        with:
-          # Can be "open", "closed", or "all".  Defaults to "open".
-          state: open
+      # - name: Find Current Pull Request
+      #   uses: jwalton/gh-find-current-pr@v1.2.1
+      #   id: findPr
+      #   with:
+      #     # Can be "open", "closed", or "all".  Defaults to "open".
+      #     state: open
       # This will echo "Your PR is 7", or be skipped if there is no current PR.
 
       - run: echo "Your PR is ${PR}"
@@ -72,6 +74,7 @@ jobs:
           PR: ${{ steps.findPr.outputs.pr }}
 
       - uses: actions/github-script@v3
+        if: success() && steps.findPr.outputs.number
         env: 
           PR: ${{ steps.findPr.outputs.pr }}
         with:
@@ -82,7 +85,7 @@ jobs:
             const fs = require('fs')
             const data = fs.readFileSync('coverage.txt', 'utf8')
             const lint = fs.readFileSync('lint.txt', 'utf8')
-            
+
             github.issues.createComment({
               issue_number: context.issue.number,
               owner: context.repo.owner,
@@ -90,17 +93,20 @@ jobs:
               body: `## Building report (PR: ${PR}): 
               
 
-              ## Linter
+              ### Linter
               <details>
-                <summary></summary>
-                {{lint}}
+                <summary> Summary </summary>
+                ${lint}
               </details>
 
 
-              ## Coverage
+              ### Coverage
               \`\`\`
               ${data}
               \`\`\`
               `
             })
+      # - name: Check on tests failures
+      #   if: job.steps.tests.status == failure()
+      #   run: exit 1  
         
